//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteDbSandbox.SQLiteStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TabstractAnalyticsEntities : DbContext
    {
        public TabstractAnalyticsEntities()
            : base("name=TabstractAnalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentProcessingEvent> DocumentProcessingEvent { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
