//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteDbSandbox.SQLiteStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProcessingEvent
    {
        public System.Guid Id { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string DocumentName { get; set; }
        public long DocumentSizeInBytes { get; set; }
        public int DocumentNumberOfPages { get; set; }
        public bool ProcessingResultHasSucceeded { get; set; }
        public string ProcessingResultErrorMessage { get; set; }
        public string ProcessingResultErrorDetails { get; set; }
        public long ProcessingResultDuration { get; set; }
        public int ProcessingResultNumberOfTablesFound { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
